### ISSUE TITLE
Extension selection of interrupt gpio

### ISSUE THREAD

**Issue by chris8519** [redplc/node-red-contrib-redplc-rpi-pcf8574#1]
Hi,
I am using the following map with int pin
https://www.horter-shop.de/de/i2c-hutschienen-module/105-bausatz-i2c-digital-input-modul-4260404260714.html

Could the node be expanded by selecting a gipo pin for int
Many greetings

**Comment by redplc** [comment]
Hi,
Sorry if I don't understand your question.
You can write me also in german.
The node-red-contrib-redplc-rpi-pcf8574 don't use the pcf8574 int pin.
All pins of pcf8574 are read in interval and stored in array.
Viele Grüße, Many greetings
